name: on_pull_request
on:
  pull_request:
    branches: [master]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Install Requirements
        run: |
          mkdir -p $HOME/bin
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          poetry install
      - uses: actions/checkout@v2
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run pylint -j 0 --ignore=vendor cliche | reviewdog -reporter=github-pr-check -diff="git diff master" -efm="%f:%l:%c: %m"
